export const SET_SOURCE = 'SET_SOURCE';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_DEPARTURE = 'SET_DEPARTURE';
export const SET_RETURN = 'SET_RETURN';
export const SET_DEPARTURE_FLIGHT = 'SET_DEPARTURE_FLIGHT';
export const SET_RETURN_FLIGHT = 'SET_RETURN_FLIGHT';
export const SET_TICKET_QUANTITY = 'SET_TICKET_QUANTITY';
export const SET_USER = 'SET_USER';